### ISSUE TITLE
Node list not showing

### ISSUE THREAD

**Issue by OlegMakarenko** [symbol/explorer#1020]
![image](https://user-images.githubusercontent.com/33131259/150151485-8dcf33bd-ef74-4466-8c4d-42ad2153f0bc.png)

```
Pagination.js:165 TypeError: Cannot read properties of undefined (reading 'restGatewayUrl')
    at Function.formatNodeInfo (NodeService.js:110:35)
    at NodeService.js:68:64
```

**Comment by cryptoBeliever** [comment]
This one is fixed.
