### ISSUE TITLE
Partial transactions list for account not presented

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/explorer#1106]
Steps to reproduce:
- Init aggregate bonded that require additional signatures from the wallet (for example for 2 of 2 multi-sig) and don't sign it.
- Open account with partial transactions in explorer (transaction will expire but check screenshot):
- In Transaction list component change filter by "Partial" transactions

Result: Transactions are not presented (Transactions component disappear)

https://testnet.symbol.fyi/accounts/TDX2TR7SYUSJTWRGKTYLP6Z64OCZHC3PIOPJYPA

In the console I can see error:
```
Pagination.js:164 TypeError: Cannot read properties of undefined (reading 'length')
    at Function.l [as fromString] (long.js:221:13)
    at Function.isLongNumericString (UInt64.js:74:33)
    at Function.fromNumericString (UInt64.js:62:21)
    at h (CreateTransactionFromDTO.js:95:124)
    at m (CreateTransactionFromDTO.js:199:26)
    at Http.js:125:48
    at Array.map (<anonymous>)
    at l.toPage (Http.js:125:37)
    at TransactionHttp.js:135:83
    at l.<anonymous> (Http.js:107:25)
```

**Comment by AnthonyLaw** [comment]
Due to REST missing the `meta` field from the partial transaction, cause the SDK breaks the explorer.

https://discord.com/channels/856325968096133191/865180563433979904/1016256170996023296
