### ISSUE TITLE
Errors in Chrome console

### ISSUE THREAD

**Issue by cryptoBeliever** [symbol/explorer#1110]
Steps to reproduce:
- search for address e.g. NAEONUNX6LVVPOIA5OK3KGO3PEWXWQZC2ATFMAI

Result:
In the Chrome console we can see the error:

```
TypeError: a.map is not a function
    at RestrictionService.js:33:61
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

===

Steps to reproduce: 
- search for address e.g. NBIOMA6OIJDQFJPUJ5UVTRS7QC7XFU3RNHXNM7Y

Result: 
In the Chrome console we can see the errors:

```
Cannot read properties of undefined (reading '0')
    at alias (AccountBalanceWidget.vue:90:1)
    at rr.get (vue.runtime.esm.js:4495:25)
    at rr.evaluate (vue.runtime.esm.js:4597:21)
    at a.alias (vue.runtime.esm.js:4851:17)
    at fn (AccountBalanceWidget.vue?b2aa:1:727)
    at r (vue.runtime.esm.js:2605:37)
    at a.Me [as _t] (vue.runtime.esm.js:2701:7)
    at a.i (Card.vue?0da0:1:466)
    at a.On.t._render (vue.runtime.esm.js:3569:22)
    at a.r (vue.runtime.esm.js:4081:21)
```

```
Error: Address is not a multisig account.
    at MultisigService.js:37:11
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:29:9)
```

```
Account restrictions are not available.
    at RestrictionService.js:30:11
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.throw (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at c (asyncToGenerator.js:29:9)
```

===

Steps to reproduce:
- open mosaics list
- open mosaic detail for any mosaic (e.g. 45CC126C4BB8C78D)

You can see errors in logs:

```
Cannot read properties of undefined (reading 'length')
    at e.<anonymous> (chunk-73c79dc9.c582aa9d.js:1042:100)
    at f (regeneratorRuntime.js:86:17)
    at Generator._invoke (regeneratorRuntime.js:66:24)
    at Generator.next (regeneratorRuntime.js:117:21)
    at r (asyncToGenerator.js:3:20)
    at s (asyncToGenerator.js:25:9)
```

**Comment by cryptoBeliever** [comment]
@AnthonyLaw please review if those errors are expected.

**Comment by AnthonyLaw** [comment]
Good catch! 👍🏼 
I have done the checking with the latest branch in my local.

For 1, 3:
-  Errors are valid. I will fix it.

For 2:
- `Address is not a multisig account.` and `Account restrictions are not available.` is expected.
- `Cannot read properties of undefined (reading '0')` it didn't display in my local.

**Comment by cryptoBeliever** [comment]
@AnthonyLaw regarding 2 I have it on https://deploy-preview-1109--explorer-dev.netlify.app/ when for address details view for address NBIOMA6OIJDQFJPUJ5UVTRS7QC7XFU3RNHXNM7Y
